export const LOG_IN_FETCHING = 'LOG_IN_FETCHING';
export const LOG_IN_FULFILLED = 'LOG_IN_FULFILLED';
export const LOG_IN_REJECTED = 'LOG_IN_REJECTED';
export const REVALIDATE_TOKEN_FETCHING = 'REVALIDATE_TOKEN_FETCHING';
export const REVALIDATE_TOKEN_FINISHED = 'REVALIDATE_TOKEN_FINISHED';
