export const LOG_IN_FETCHING = 'LOG_IN_FETCHING';
export const LOG_IN_FULFILLED = 'LOG_IN_FULFILLED';
export const LOG_IN_REJECTED = 'LOG_IN_REJECTED';
export const REGISTER_FETCHING = 'REGISTER_FETCHING';
export const REGISTER_REJECTED = 'REGISTER_REJECTED';
export const LOG_OUT = 'LOG_OUT';
