export const GET_EXPENSES_FETCHING = 'GET_EXPENSES_FETCHING';
export const GET_EXPENSES_FULFILLED = 'GET_EXPENSES_FULFILLED';
export const GET_EXPENSES_REJECTED = 'GET_EXPENSES_REJECTED';

export const ADD_EXPENSES_FETCHING = 'ADD_EXPENSES_FETCHING';
export const ADD_EXPENSES_FULFILLED = 'ADD_EXPENSES_FULFILLED';
export const ADD_EXPENSES_REJECTED = 'ADD_EXPENSES_REJECTED';

export const UPDATE_EXPENSES_FETCHING = 'UPDATE_EXPENSES_FETCHING';
export const UPDATE_EXPENSES_FULFILLED = 'UPDATE_EXPENSES_FULFILLED';
export const UPDATE_EXPENSES_REJECTED = 'UPDATE_EXPENSES_REJECTED';

export const DELETE_EXPENSES_FETCHING = 'DELETE_EXPENSES_FETCHING';
export const DELETE_EXPENSES_FULFILLED = 'DELETE_EXPENSES_FULFILLED';
export const DELETE_EXPENSES_REJECTED = 'DELETE_EXPENSES_REJECTED';
