export const GET_FAVORITE_COINS_FETCHING = 'GET_FAVORITE_COINS_FETCHING';
export const GET_FAVORITE_COINS_FULFILLED = 'GET_FAVORITE_COINS_FULFILLED';
export const GET_FAVORITE_COINS_REJECTED = 'GET_FAVORITE_COINS_REJECTED';

export const UPDATE_FAVORITE_COINS_FETCHING = 'UPDATE_FAVORITE_COINS_FETCHING';
export const UPDATE_FAVORITE_COINS_FULFILLED =
  'UPDATE_FAVORITE_COINS_FULFILLED';
export const UPDATE_FAVORITE_COINS_REJECTED = 'UPDATE_FAVORITE_COINS_REJECTED';

export const RESET_FAVORITES_UPDATED = 'RESET_FAVORITES_UPDATED';
