export const GET_INCOME_FETCHING = 'GET_INCOME_FETCHING';
export const GET_INCOME_FULFILLED = 'GET_INCOME_FULFILLED';
export const GET_INCOME_REJECTED = 'GET_INCOME_REJECTED';

export const ADD_INCOME_FETCHING = 'ADD_INCOME_FETCHING';
export const ADD_INCOME_FULFILLED = 'ADD_INCOME_FULFILLED';
export const ADD_INCOME_REJECTED = 'ADD_INCOME_REJECTED';

export const RESET_INCOME_ADDED = 'RESET_INCOME_ADDED';
export const RESET_INCOME_DELETED = 'RESET_INCOME_DELETED';
export const RESET_INCOME_UPDATED = 'RESET_INCOME_UPDATED';

export const UPDATE_INCOME_FETCHING = 'UPDATE_INCOME_FETCHING';
export const UPDATE_INCOME_FULFILLED = 'UPDATE_INCOME_FULFILLED';
export const UPDATE_INCOME_REJECTED = 'UPDATE_INCOME_REJECTED';

export const DELETE_INCOME_FETCHING = 'DELETE_INCOME_FETCHING';
export const DELETE_INCOME_FULFILLED = 'DELETE_INCOME_FULFILLED';
export const DELETE_INCOME_REJECTED = 'DELETE_INCOME_REJECTED';
