const modalTypes = {
  ADD_INCOME: 'ADD_INCOME',
  DELETE_INCOME: 'DELETE_INCOME',
  UPDATE_INCOME: 'UPDATE_INCOME',
  ADD_EXPENSES: 'ADD_EXPENSES',
  DELETE_EXPENSES: 'DELETE_EXPENSES',
  UPDATE_EXPENSES: 'UPDATE_EXPENSES'
};

export default modalTypes;
