export const GET_SPONSORS_FETCHING = 'GET_SPONSORS_FETCHING';
export const GET_SPONSORS_FULFILLED = 'GET_SPONSORS_FULFILLED';
export const GET_SPONSORS_REJECTED = 'GET_SPONSORS_REJECTED';

export const ADD_SPONSORS_FETCHING = 'ADD_SPONSORS_FETCHING';
export const ADD_SPONSORS_FULFILLED = 'ADD_SPONSORS_FULFILLED';
export const ADD_SPONSORS_REJECTED = 'ADD_SPONSORS_REJECTED';

export const RESET_SPONSORS_ADDED = 'RESET_SPONSORS_ADDED';
export const RESET_SPONSORS_DELETED = 'RESET_SPONSORS_DELETED';
export const RESET_SPONSORS_UPDATED = 'RESET_SPONSORS_UPDATED';

export const UPDATE_SPONSORS_FETCHING = 'UPDATE_SPONSORS_FETCHING';
export const UPDATE_SPONSORS_FULFILLED = 'UPDATE_SPONSORS_FULFILLED';
export const UPDATE_SPONSORS_REJECTED = 'UPDATE_SPONSORS_REJECTED';

export const DELETE_SPONSORS_FETCHING = 'DELETE_SPONSORS_FETCHING';
export const DELETE_SPONSORS_FULFILLED = 'DELETE_SPONSORS_FULFILLED';
export const DELETE_SPONSORS_REJECTED = 'DELETE_SPONSORS_REJECTED';
